# estágios da pipeline
stages:
  - test

# job responsável pela execução dos testes e2e
e2e-tests:

  # estágio que o job pertence
  stage: test

  # imagem Docker utilizada na execução
  image: node:24

  # comandos executados antes dos testes
  before_script:

    # instalação do Yarn
    - npm install -g yarn

    # instalação das dependências do projeto
    - yarn install

    # instalação dos browsers do Playwright
    - yarn playwright install

  # comandos principais do job
  script:

    # execução dos testes e2e
    - yarn run e2e

  # execução manual da pipeline
  # equivalente ao workflow_dispatch do GitHub Actions
  when: manual